### ISSUE TITLE
Could `Migrations` be optional?

### ISSUE THREAD

**Issue by EwanValentine** [encoredev/encore#1129]
Hi there, first of all, excellent work on an excellent service! 

Just a quick question. For creating databases, is it possible to make `Migrations` optional at all? I'm just using the `gorm.AutoMigrate` method for a simple project, but... `NewDatabase` seems to require `Migrations` to be set. If I set it, then have an empty directory `./migrations`, then I get a deployment error saying something like: `no such file or directory: migrations`.

```go
var serviceDB = sqldb.NewDatabase("service", sqldb.DatabaseConfig{
	Migrations: "./migrations",
})
```

To get around this I'm currently creating a `migrations` directory, and just including a blank migration in there with just `BEGIN;COMMIT;`.  

So yeah, just wondered if it would be possible for that to be optional? Happy to do the PR, just wondered if there was a reason that wasn't the case already before I did

**Comment by eandre** [comment]
Hey @EwanValentine! We have plans on making the migrations directory optional. That said, `gorm.AutoMigrate` isn't a good fit for cloud deployments because Encore sets up the roles and permissions in a way that the running service doesn't have permissions to modify the table schema, as part of security best practices.

For the use case you describe, we recommend using [Atlas + GORM](https://encore.dev/docs/how-to/atlas-gorm) to automatically create migration files representing the GORM table structure.
