### ISSUE TITLE
Add Typespec.io support for APIs and types 

### ISSUE THREAD

**Issue by ahmadalibaloch** [encoredev/encore#1201]
Are there any plans to use typespec.io?

**Comment by eandre** [comment]
We're currently focused on supporting describing APIs using plain TypeScript. Typespec.io is certainly interesting, and we may add support for it in the future, but it doesn't currently seem to offer much additional functionality beyond what Encore already supports.

**Comment by magiconair** [comment]
I would like to offer a different opinion here. 

Typespec allows a Schema First approach when modeling APIs with the ability to define patterns for APIs to enforce URL structures, parameters, return types and response codes. This means that APIs are more consistent across services. For example, we can build a pattern which automatically uses the same pagination for all `list` operations, return `201 Created` for all Create operations, and have consistent error messages across all APIs. 

This is supported through tooling instead of code reviews and developer education which is a benefit in larger systems with several distributed teams and lots of services. Otherwise, we have to rely on developers in different teams to do the right thing. 

Encore currently does not seem to offer something to support this but maybe I'm missing something here.

One way Encore might implement this is through supporting annotations on interfaces in addition to functions/methods since these interfaces could be generated through a TypeSpec emitter. Something like this:

```go
// hello_service_gen.go
// generated by TypeSpec emitter
package hello

import (
	"context"
)


type Hello interface {
	//encore:api public path=/hello/:name
	World(ctx context.Context, name string) (*Response, error)
}

type Response struct {
	Message string
}

// hello.go
package hello

import (
	"context"
)

type HelloService struct{}

func (h *HelloService) World(ctx context.Context, name string) (*Response, error) {
	msg := "Hello, " + name + "!"
	return &Response{Message: msg}, nil
}
```

**Comment by magiconair** [comment]
Here is another idea on approaching this. Assuming we can generate this from TypeSpec

```go
package machines

import "context"

type Machines interface {
	ReadMachine(ctx context.Context, name string) (*Machine, error)
}

//encore:service
type Service struct {
	impl *Impl
}

var _ Machines = (*Service)(nil)

//encore:api public path=/machines/:name
func (s *Service) ReadMachine(ctx context.Context, name string) (*Machine, error) {
	return s.impl.ReadMachine(ctx, name)
}

type Machine struct {
	Id  string
}
```

Then we can write an implementation like this:

```go
package machines

import "context"

type Impl struct{}

var _ Machines = (*Impl)(nil)

func (i *Impl) ReadMachine(ctx context.Context, id string) (*Machine, error) {
	msg := "Hello, " + id + "!"
	return &Machine{Id: msg}, nil
}
```
