### ISSUE TITLE
Remove enforcing `encore.service.ts` filename in favour of `*.service.ts`

### ISSUE THREAD

**Issue by seivan** [encoredev/encore#1326]
I am not a huge fan of forced naming conventions when they're not unique. Like having 50`mod.rs`  or `index.ts` files. 
Rust fixed it by just letting you name the file outside of the folder. 
Maybe that's a solution? 
Otherwise, maybe it could just be a glob check, so it could be called `trello.service.ts`. 

Afaik the code referenced here seems like it would allow `trello.encore.serivce.ts` since it uses `ends_with`, but I am not sure if I caught them all. If that is the case maybe the docs need to be updated, otherwise are you guys open for a change? 

https://github.com/encoredev/encore/blob/fa4f68a142713216d52182e5724d0c2773921425/tsparser/src/parser/parser.rs#L139
https://github.com/encoredev/encore/blob/fa4f68a142713216d52182e5724d0c2773921425/tsparser/src/parser/resources/apis/service.rs#L52

**Comment by eandre** [comment]
This was by design. Since the name of the service is listed in the source code we didn't want to also name the file `foo.service.ts` as it allows for divergence. In my experience most editors handle this quite well, and typically when you have multiple files open with the same name the editor also lists the directory name.

I agree there are downsides to this approach, and I certainly share your frustration with the amount of `mod.rs` files, but defining a service is much less common than defining a Rust module, so the problem should be much less severe.

`ends_with()` on `Path` checks for an exact match on the last path segment, so it doesn't allow for `foo.encore.service.ts`.

**Comment by seivan** [comment]
Fair enough, I guess you’re right that it won’t be as prevalent as mod. Thanks.
