### ISSUE TITLE
`private` APIs require struct parameters

### ISSUE THREAD

**Issue by anfragment** [encoredev/encore#1377]
## Description
Functions marked with the `//encore:api private` compiler directives that accept non-struct arguments cause the error `Invalid request type: API request types must be named structs`:
```go
//encore:api private
func StringParam(ctx context.Context, id string) error {
	return nil
}
```
=>
<img width="573" alt="image" src="https://github.com/user-attachments/assets/04c1444d-b0aa-4d37-b336-14112a335d7f">

This seems like a strange limitation for something that might only be called internally by the code itself, so I’m wondering if it’s the intended behavior.

Furthermore, adding `method` and `path` to the directive allows the CLI to go ahead and generate the intended function interface inside `encore.gen.go`, even though they serve no purpose for private APIs.

## Steps to reproduce
1. Clone [anfragment/encore-bug-demo](https://github.com/anfragment/encore-bug-demo).
2. Run `encore gen wrappers` to trigger the error.
3. Append `method=GET path=/:id` to [`svc.go:5`](https://github.com/anfragment/encore-bug-demo/blob/master/svc/svc.go#L5).
4. Run `encore gen wrappers` to get `encore.gen.go` generated.

## Expected behavior
The `//encore:api private` compiler directive should accept non-struct arguments without throwing an error.

## Additional context
- encore version v1.40.5
- go version go1.23.1 darwin/arm64

**Comment by eandre** [comment]
This is by design; to use arguments like this you have to specify that they're part of the path, like you mentioned. This works:

```go
//encore:api private path=/string-param/:id
func StringParam(ctx context.Context, id string) error {
	return nil
}
```

The reason for this is to ensure APIs are developed in a way that is forward and backward compatible.

The example you gave (without the path parameter) would have to send the `id` as a JSON string in the request body. It's very difficult to change this to e.g. accept an object in the future without breaking the JSON unmarshalling: a string cannot be decoded into an object. By enforcing that all JSON bodies are objects, it's much easier to reason about backwards and forwards compatibility, and you can safely introduce new fields and deprecate old fields within that object.

Hope that makes sense.

**Comment by anfragment** [comment]
Oh, so despite the generated bindings these private APIs get called with HTTP? Is it the case that different services can/do run within different processes?

**Comment by anfragment** [comment]
Got it, makes sense. Thank you!
