### ISSUE TITLE
`//encore:api auth` and `AuthHandler()` when you have multiple AuthN types/systems

### ISSUE THREAD

**Issue by GavinRay97** [encoredev/encore#16]
Heya, saw your announcement on HN and the out-of-the-box functionality in encore looks great!

Reading through the docs, one question I had was how to address a scenario like this:
- You run a business which has multiple AuthN systems. (Let's pretend we own a chain of fitness centers or sell software for them)
- Fitness center employees login via a typical email/password authentication system
- Fitness center members use a phone app and are auth'ed via SMS OTP system
- Developers or sysadmins have yet another portal which is separate from either of these

In an implementation for something like this, I'd have 3 separate auth modules/endpoints.

Is there any non-hacky way to do this (IE, not by sending `X-Authentication-Type` header or something on the request context, and having a single endpoint that has a polymorphic request + response payload dependent on header value)?

These comment-directive things seem useful but I wonder if maybe there's not some way to allow folks to define their own/new ones?

Similar to Custom Decorators in Nest.js (which is a Spring clone):
https://docs.nestjs.com/custom-decorators

```ts
// Create @User decorator
export const User = createParamDecorator(
  (data: string, ctx: ExecutionContext) => {
    const request = ctx.switchToHttp().getRequest()
    const user = request.user

    return data ? user?.[data] : user
  },
);

// Create @Auth decorator
export function Auth(...roles: Role[]) {
  return applyDecorators(
    SetMetadata('roles', roles),
    UseGuards(AuthGuard, RolesGuard),
    ApiBearerAuth(),
    ApiUnauthorizedResponse({ description: 'Unauthorized' }),
  )
}
```
```ts
@Get()
@Auth('user')
async findOne(@User('firstName') firstName: string) {
  console.log(`Hello ${firstName}`)
}
```

Thanks =D
Gavin

**Comment by eandre** [comment]
Hey Gavin, thanks for the detailed use case!

In my experience it's pretty common to have different types of users or tokens, and encode that information into the token itself. See [https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/](GitHub's new authentication token formats) for a recent example.

In that case you would have a single entrypoint which can handle all types of tokens. That would correspond to a single `encore:authhandler` implementation. I would then define [https://encore.dev/docs/concepts/auth#with-custom-user-data](Encore custom user data) that includes information about what type of user it is. Your `auth-required` endpoints would then check against this to determine what to do.

There's currently no way to define "decorators". It goes a bit against Go's philosophy, and we're trying to stay as close to the language philosophy as we can (but being pragmatic since we're operating in a more specific domain). It's something we can consider, but since Encore was just released we lack enough data to make an informed decision about how common that use case is right now.

Does that make sense? Or did I misunderstand what you were asking?

**Comment by GavinRay97** [comment]
Ah okay, I think I get it.

So best-practice here would be to have a single auth endpoint and handle everything through that.

Thank you!
