### ISSUE TITLE
path in api definition can't use anything other than string literals

### ISSUE THREAD

**Issue by deathcrafter** [encoredev/encore#1637]
I am aware that `api`s are passed off to Rust for pre-processing and stuff, but that hampers the usability of the very thing.

Now I wanted to have a base path functionality since _it's not a in-built feature_ **which it should be.** You can say it's opinionated, but the framework itself is opinionated so it wouldn't hurt to have options.

Anyways, the implementation was something like this:
```ts
function basePath(base: string) {
  return (path: string) => base + path;
}

const routeBase = basePath("/some");

const someApi = api({path: routeBase("/route")}, () => {});
```

Now of course it wouldn't work and I have to do some very complex regex replace operation when I want to change `/some` to `/some2` in the IDE instead of just simply changing a value.

**Comment by eandre** [comment]
I agree it would be nice to support in some way. It's a bit tricky since we want to preserve the ability to statically analyze the code to determine what paths exist. 

That said, I don't think changing the base prefix is a very common thing to do. It breaks all clients unless you take care to introduce aliases, but if you do that you're already doing something more nuanced that requires some care.

**Comment by deathcrafter** [comment]
That makes sense. I'm closing this issue for now as it seems this is not really an issue.
