### ISSUE TITLE
Foreign keys between services is not possible

### ISSUE THREAD

**Issue by Minivera** [encoredev/encore#28]
I have two services, one called `identity` where I store my user information, and one called `content` where I store user generated content. In both services, I have a few migrations that create the tables and indexes in my database, for example:

In the identity service:
```sql
CREATE TABLE "users" (
   id BIGSERIAL PRIMARY KEY,
   ...
);
```

And then in the content service:

```sql
CREATE TABLE "documents" (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGSERIAL NOT NULL,
    ...
);
```

In the `documents` table, I'd want to add a constraint to set my foreign key do to things like cascade deletes, something like: `CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES "identity"."users"(id) ON DELETE CASCADE`.

That would be doable even with micro-services by having all services use the same DB, but isolate the data in different schemas. With encore however, it seems the services instead use different databases on the same server, which makes these kind of indexes or constraints impossible. Looking at the code, we can see the deamon setting this up as [different database systems](https://github.com/encoredev/encore/blob/82b6d7efbdf5c8625ab92dd1c80f1370110afa32/cli/daemon/sqldb/cluster.go#L195).

I found it a bit confusing when trying to connect to my databases with a database client or my IDE (Since I needed to create one connection per service), but it's not a deal breaker. Not being able to create foreign keys is a bit more annoying though. This limitation also means that joins are not possible either.

Is there any reason why this decision was made? (Not asking as a trick question, I am genuinely curious) Would having each service run on isolated schemas on the same database rather than different schemas be something you could envision for encore? I'm happy to make a PR if you feel this could be changed.

**Comment by eandre** [comment]
The reason this isn't possible comes directly from the fact that distinct services have their own databases. This is the case because, generally speaking, if you break something apart into different services it's to signify that they should be isolated from each other. Often this is for organizational reasons when you have multiple dev teams, but even at smaller scales some sort of isolation tends to be the driving factor behind breaking things apart.

Having independent services then use the same database tends to be a bit of an anti-pattern for that reason. That said, we do intend on supporting this use case and other related use cases where you want to connect to a shared database, and in fact it's likely the very next feature we're shipping, hopefully this week but possibly the week after.

While Encore makes it really easy to define separate services, it's not opinionated about whether you create "microservices" or "macroservices" or something in-between. I personally tend to think fewer, larger services are easier to reason about. Perhaps your use case would be easier by actually having a single service, which would enable you to define foreign keys between these tables. You can still break your service apart into multiple components, using packages within the service directory.

*(The only caveat is that the APIs you define for the service must be defined in the same package, but within that you can have subdirectories with different packages which all reference the same database.)*

**Comment by Minivera** [comment]
> Perhaps your use case would be easier by actually having a single service, which would enable you to define foreign keys between these tables. You can still break your service apart into multiple components, using packages within the service directory.

That's what I did originally yeah, I changed it as I found that it made the documentation a lot harder to parse. I have a dozen endpoints or so and having them into microservices like this made it so endpoints are neatly divided into "categories" on the documentation side. It's a lot nicer that way. Though now that I talk about it in the context of this issue, that might be a symptom of a different root problem with how documentation are generated. Maybe something like a `//encore:tag Content` annotation or having the parser take subpackages into account (Is it possible it can already do that? I haven't tested this yet) would work much better than dividing things into services :thinking: .

To go back to the topic, I can totally see where that decision came from. I'll look forward to the new feature! In the context of aggregation APIs like a GraphQL API, using joins can really made a massive difference in terms of performance, it can be worth the loss in isolation.

**Comment by eandre** [comment]
Agreed completely, and we definitely want to make it possible to express relationships between databases, even though it's impossible to define foreign key constraints across databases. Will close this issue for now as the original question has been addressed, but re-open if you feel otherwise :) thanks!
