### ISSUE TITLE
Improved feedback for db migrations.

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [encoredev/encore#30]
When you run `encore run` if you have new db migrations, the daemon sort of hangs for a couple of seconds (whilst the migrations run) but you get no feedback of this.  I think  log lines such as 
` running migration 3_adding_new_thing.up.sql` would go a long way.

Secondly, if your migration does fail you get surfaced the error directly from go-migrate. I think adding a trouble shooting doc to the site of how to get out of this dirty state would be a welcome addition.

If you think the above issues are good ideas, I'm happy to work on them.

**Comment by eandre** [comment]
Thanks @MatthewJamesBoyl, I agree completely and those would be great additions.

On the topic of outputting information about what's happening behind the scenes, there's also the issue of the very first run being quite slow (possibly due to compiling the standard library?). Looking into if we could give the user feedback about this would also be useful.

If you're willing to help that would be very appreciated!

**Comment by eandre** [comment]
In the next release of Encore we have drastically improved the amount and quality of feedback when running `encore run`, including tracking the progress of running database migrations. I'm coming to close this as that was the main concern here, but will open a separate ticket to track the documentation work around handling dirty database migrations. Thank you!
