### ISSUE TITLE
FTL could not run error=EOF

### ISSUE THREAD

**Issue by sbdchd** [encoredev/encore#325]
I'm not sure what FTL is but the error message for it is a little terse

The hot reloading still seems to be working even though the error is being logged.

```
Changes detected, recompiling...
6:18PM FTL could not run error=EOF
Reloaded successfully.
6:18PM INF registered API endpoint endpoint=World path=/hello/:name service=hello
6:18PM INF listening for incoming HTTP requests
6:18PM INF starting request endpoint=World service=hello
6:18PM INF request completed code=ok duration=1001.523708 endpoint=World service=hello
```

**Comment by eandre** [comment]
Hey Steve, thanks for the bug report! This is a harmless log message, and it's due to the app logging a spurious error during graceful shutdown. It's already fixed in the upcoming release next week. FTL is shorthand for log-level fatal, which comes from Encore's use of github.com/rs/zerolog. Sorry for the confusion!
