### ISSUE TITLE
Copy as cURL does not work when using structs for GET requests

### ISSUE THREAD

**Issue by bih** [encoredev/encore#384]
Returns the correct result when running through the Local Developer Dashboard, but not when copying the cURL command for a GET endpoint with parameters. The equivalent cURL command that it is rendering is:

```sh
curl 'http://localhost:4000/schedules?Start=2022-09-28T23%3A00%3A00Z&End=2022-12-09T23%3A30%3A00Z'
```

And renders this error in my system (which does not appear when running in the local developer dashboard as you can see below):

```json
{
  "code": "unknown",
  "message": "start time cannot be equal to end time",
  "details": null
}
```

<img width="1239" alt="Screenshot 2022-09-22 at 17 25 54" src="https://user-images.githubusercontent.com/918552/191801487-a497d3da-aa48-43dc-9f23-554bf1494fb2.png">

**Comment by teleivo** [comment]
Hi @bih 😄 I'd like to have a look at this one if that is ok.

**Comment by teleivo** [comment]
@bih the error you are seeing might be due to the query parameters not being converted to snake-case as described in https://encore.dev/docs/develop/api-schemas#query-parameters

So if I lowercase the `TimeRange` struct fields `Start` and `End` to and adjust the `end` date as its default is the same as the `start` date:

```
curl 'http://localhost:4000/schedules?start=2009-11-10T23%3A00%3A00Z&end=2022-11-10T23%3A00%3A00Z'
```

the request is successful and shows the same result as in the UI 😄
