### ISSUE TITLE
bug: unnamed type in response struct

### ISSUE THREAD

**Issue by MaxDanielsson** [encoredev/encore#441]
Encore panics when running `encore run`, reported as to follow the directions from the error itself 

<img width="936" alt="Screenshot 2022-10-14 at 13 46 21" src="https://user-images.githubusercontent.com/33028551/195839430-eb57d974-43ed-495c-9b59-4e2b524ff346.png">

**Comment by Minivera** [comment]
I think the issue here is the response type _has_ to be a struct, nothing else. In your case, it looks like it's a slice?

Maybe try creating an intermediary struct like

```go
type Response struct {
  results [models.OptResult]
}
```

You might also run into issues as it looks like you've for multiple response types. I think you'll want to add the `modles.EnvMetrics` and the transportation.GetTotalCostResponse` to that intermediary struct.

**Comment by eandre** [comment]
Yes, what @Minivera said is the issue I believe. Closing this with that assumption, but please reopen if it's not the case. Thanks!
