### ISSUE TITLE
Dashboard API Docs sidebar not scrolling as expected

### ISSUE THREAD

**Issue by melkstam** [encoredev/encore#61]
The sidebar for the API Docs in the dashapp has `position: sticky`. This works well for when the sidebar content fits onto the screen, but when it doesn't it doesn't scroll independently from the main content (like it does for the Encore docs or the API Docs on app.encore.dev). So for when the main content is large (> 50000 px for us at the moment), you have to scroll all the way down to be able to see what was out of the screen initally on the sidebar.

**Comment by eandre** [comment]
Thanks @vilhelmmelkstam, that's a great point. We need to make them scroll independently of each other.

**Comment by simon-johansson** [comment]
@melkstam I have been working on applying the Encore branding to the local dev dash. This problem is now hopefully resolved (see video below). The new styling should be available soon, in the next release of the CLI.

![2022-09-21 10 35 57](https://user-images.githubusercontent.com/1826823/191460769-bd8c8264-6ff0-492c-8ec0-f829dc6aeee9.gif)
